GET http://localhost:3030/settings

###

POST http://localhost:3030/settings
Content-Type: application/json

{
    "show_tags": false
}


###

GET http://localhost:3030/aircraft

###

POST http://localhost:3030/aircraft
Content-Type: application/json

{
    "name": "ac_a",
    "latitude": 13.34,
    "longitude": 165.12,
    "altitude": 4032.1
}

###

POST http://localhost:3030/aircraft
Content-Type: application/json

{
    "name": "ac_b",
    "latitude": 13.5,
    "longitude": 165.12,
    "altitude": 4032.1
}


###

POST http://localhost:3030/log

random data

and stuff